### ISSUE TITLE
`fuelup` - forc binary distribution and toolchain manager

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuelup#1]
We need a version manager similar to `rustup` that allows downloading, installing, and managing different versions of the compiler and `forc`. I suggest calling this `forcup`.

For now, the version manager should be able to:
- [ ] Download a toolchain for a provided architecture from GitHub (depends on FuelLabs/sway#1191). The toolchain includes a docs directory.
- [ ] Also download plugins (`forc-fmt`, `forc-lsp`, etc.).
- [ ] Set the default toolchain version.
- [ ] Enable reading of the default toolchain version (so that `forc` can detect when you're using the wrong version that doesn't match what's configured in the manifest file).

**Comment by adlerjohn** [comment]
Yes, the compiled mdbook files. This can be deferred to a future PR.

**Comment by binggh** [comment]
(Going to use this as somewhat of a tracking issue, so I'm posting my discussion here 😅 )

## Toolchain version management & what a stable toolchain means

Had a short chat with @mitchmindtree regarding how the toolchain should look like. Would love to get more ideas on this topic of toolchain versioning and management. The main question for us in my mind is: what would constitute as stable toolchain? #6 

@mitchmindtree brought up a good point that `forc` and `fuel-core` are meant to be independent projects i.e. in future Sway can also target other VMs, but they are also meant to work together right now. In which case the onus might be on us to define what a stable toolchain is i.e. do we want to package specific versions of `forc`, `forc-fmt`, `fuel-core` etc. together ourselves and label it as stable, or do we want to allow devs to freely control versioning of each of the above crates? At first I thought the second approach seemed nicer since it gave granular control but later on Mitch convinced me that the first approach is better as `fuelup` is meant to be as simple as possible for devs to use - in that case we should probably minimise the number of active decisions they make when using the toolchain.

@mitchmindtree gave a few suggestions:

1) depending on whether we use `stable` or `nightly`, we first pick the appropriate `forc`, then we pick whichever latest `stable` or `nightly` release of `fuel-core`
2) select the version of `fuel-core` from the `forc` CI (serves as a good base to work from since we would know its well tested)
3) maintain a simple file `fuel-core-version` in the Sway repo containing the semver version of `fuel-core` which we test against, then both `forc` CI and `fuelup` know which version to use from there.
 
For reference, the Rust toolchain operates on a [train schedule](https://doc.rust-lang.org/book/appendix-07-nightly-rust.html) which means the stable, beta and nightly toolchains are on a fixed schedule, and depend on not having breaking bugs to be labelled as `stable`. I'm not sure how the rust toolchain used to be like before 1.0 and how they synced - Mitch said they might not have been synced before and it's something I'll look into

**Comment by adlerjohn** [comment]
Rust `nightly` isn't the same as build-each-night. cc @mitchmindtree for more explanation.

I think we should avoid actual nightly builds against `master`, as they're not guaranteed to have any stability. Release builds are often enough that nightly builds simply aren't needed, and have at least a bit of guarantees around stability.

**Comment by mitchmindtree** [comment]
> Rust nightly isn't the same as build-each-night. cc @mitchmindtree for more explanation.

Ah, this was exactly my understanding of what nightlies were :joy: At least in the early days my understanding is that it was roughly a cron job that would build everything, run a bunch of tests, and if anything failed it would just not release that night, so the latest nightly was always whatever the most recently successful build was.

That was years ago though, I'm not aware of how Rust's nightlies operate today. @binggh would certainly be worth investigating!

**Comment by adlerjohn** [comment]
it is done
