### ISSUE TITLE
Add the forc-client plugin commands, `forc deploy`, `forc run`

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuelup#142]
### Problem you are trying to solve

This is the final step for https://github.com/FuelLabs/sway/issues/2412.

### Solution you'd like

Ensure `forc-client` plugin is shipped by default along with the rest of the forc plugins.

### Notes

Some consideration might be needed to distinguish between the "plugin" (`forc-client`) and the two command binaries it provides (`forc deploy`, `forc run`).

We should prioritise this to make sure these commands are still available on the next published release (or soon after at least).

**Comment by bingcicle** [comment]
The new binaries still execute but I discovered 2 different, tangential issues here:

1) `fuelup check --verbose` has to be updated to list `forc-deploy` and `forc-run` as `forc-client`.
2) Because of the way plugins are packaged and run through `fuelup`, `forc run --help` doesn't print help messages for example. This wasn't an issue until now when we split `forc-deploy` and `forc-run` into their own binaries, because previously the 3 plugins we had had very minimal subcommands to warrant doing a `--help`.

I'm creating 2 separate issues for the above I described. Perhaps this issue isn't relevant as well(?) since the executables do run as expected.
