### ISSUE TITLE
Add a `Plugin` abstraction that allows us to reason about plugins with multiple commands

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuelup#163]
In #152 and #154 especially we add some hacks to check for `forc-client` in order to handle its unique behaviour of providing multiple commands.

In the future, we will likely add more plugins that support multiple commands (e.g. [`forc-edit`](https://github.com/FuelLabs/sway/issues/2369)) and we should use a proper `Plugin` type (rather than just strings) that allows us to reason about this more generally.

**Comment by bingcicle** [comment]
Hmm, I'm not sure if the issue is phrased accurately. `forc-client` itself is the plugin but it is not the executable, instead it distributes 2 different binaries, `forc-deploy` and `forc-run`.

While I agree we can abstract away `Plugin`s, we'd still need some sort of map to match the above binaries to `forc-client` especially within a command like `fuelup show`.
