### ISSUE TITLE
ci: track latest releases for other components

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#377]
Currently the CI tracks only the sway and fuel-core repos for releases. This should be updated to track the other repos as well. The flow should be something like:

1) Check for **ALL** components for new releases.
2) If `forc` or `fuel-core` have new releases, we run compatibility checks on them, and publish a new `latest` channel **only if necessary**.
3) If other components have new releases, we will **always** publish a new `latest`. (This is what we lack)

**Comment by bingcicle** [comment]
this should be done once #392 is merged

**Comment by ra0x3** [comment]
- Hey @bingcicle 👋🏽 , is there any type of ETA on this? 
- With the indexer being such a young project (still on 0.5!) we're constantly pushing out new changes and updating docs for those changes. 
- However, with this lag between us publishing a new version, and that version being available on default fuelup, it can be super confusing for users -- and the indexer project is basically unusable because the docs are written for version A but fuelup has version B
- Any idea when this change might go in?
