### ISSUE TITLE
Use fuel.nix internally and deprecate current work.

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/fuelup#457]
We have decided to focus our efforts for managing the fuel toolchain around [fuel.nix](https://github.com/FuelLabs/fuel.nix/)

As such, we would like to deprecate the existing internals of `fuelup` and instead wrap the current CLI to call into `fuel.nix` directly. Although users are welcome to use fuel.nix directly, there are a large percentage of users who will still appreciate the fuelup CLI interface for it's simplicity and don't care how the toolchain is managed behind the hood.

**Comment by JoshuaBatty** [comment]
To add some more context, the main motivation is to reduce the current need to maintain both `fuelup` and `fuel.nix`. Ideally we only need to manage toolchains and patches using `fuel.nix` and `fuelup` is able to leverage that infrastructure. 

### Why even have fuelup?

One valid question is if we already have fuel.nix, why even have `fuelup`? The main motivations I can think of are:

1. ease of use
2. less complexity
3. minimal cognitive overhead to install and manage components 

### Current Approach 

The current approach I asked Austin to go in #461 was to treat fuelup as an opinionated CLI wrapper around fuel.nix itself. 

Pros: 
- Since `fuelup` would be directly calling into `fuel.nix`, there's less room for discrepancies. Both tools would remain in sync.
- By using `fuelup` as a wrapper, there's less code duplication, reducing the potential for bugs and decreasing maintenance effort.

Cons:
- We require nix to be installed on the users system.
- If there's an issue with `fuel.nix`, it might be harder to debug through the `fuelup` wrapper. It could also lead to more abstracted error messages which might be confusing for users.

I’m sure Austin can provide some more context on the pro’s and con’s of the current approach. Kaya mentioned another approach in the sync yesterday that would be great to mention here also. Would be great to get everyone’s input so we can hone in on exactly what we want fuelup to be before we go any further into the development process.

**Comment by eureka-cpu** [comment]
I believe @kayagokalp 's suggestion was in line with my original thoughts, since fuelup is already a great tool and well written and tested, why not just have fuelup fetch binaries from the `fuel.nix` channels instead of the tarballs it currently fetches?

Though I have already gone through the trouble of doing the former and updating both the install script, and creating the CLI wrapper for `fuelup nix`, I'm not opposed to it. It would simplify not only for the user, to avoid confusing nix errors which could possibly happen for reasons outside of our control (not to mention handling every possible error nix error is a slippery slope), but for development as well since it could be a much simpler task to swap where fuelup gets the binaries from than to completely deprecate an already feature complete tool with thorough tests.

Continuing down the path of a nix wrapper, we would have to get creative to reach parity with the functionality that fuelup already provides. The features I've implemented so far are a bit hacky at best. Nix uses `stderr` to show progress, which was a hurdle to overcome to meet the UX quality standards for this tool (thank you @JoshuaBatty for all the help with that).

So far the features of `fuelup nix` are as follows:
- `fuelup nix install <toolchain or component>` (currently fuelup separates this into two commands, the flake doesn't and to meet time constraints I've just ran with the default functionality)
- `fuelup nix upgrade <option<toolchain or component>>` (upgrades all packages if none are specified)
- `fuelup nix list` (currently working on this, the default nix output is _not great_ ™)
- `fuelup nix remove <index or path>` (this is the default for nix, but with the list feature complete the user can just specify the package they want to remove by name)

Drawbacks:
`nix profile` (the way nix manages binaries from the flake) has some drawbacks that have gotten in the way a bit.

If nix finds two binaries that would otherwise cause a conflict it will ask the user to either remove the old package or assign a priority to the new or old package so one takes precedence over the other. I've implemented an auto priority function to the `fuelup nix install` command so that the newest package always takes precedence and the user will never see the error.

It is possible this error will also show up for upgrading packages. 

There is also a known issue where installing the same package with a higher priority will not overwrite the old one, causing duplicates of the same binary to be installed for a profile (this will be fixed after the list functionality is complete, as it will allow me to determine whether a package already exists and remove it before installing the new one).

There is no way currently (that I can find in the docs or github issues at least) to get the priority of the packages known to nix profile, other than running into the error.

There isn't an easy way to create a custom toolchain, unlike with the original fuelup.
Some possible solutions:
1. recommend or constrain the user to only ever install one of each component, we wouldn't need to tell them but just remove a component if another is trying to be installed, eg the user has mostly `latest` toolchain components, they try to install `forc-doc-nightly` so it removes the `latest` version before installing it
2. create a nix function that will take the users input for the desired packages, and create a new derivation to be built from the flake's channels allowing for the user to specify a name for the derivation and manage it as its own toolchain
3. take in the users input for the desired packages and load a new nix shell with those packages on `PATH`

Personally I like 2 the most, it's the most _nixy_ way of doing it, but also may prove to be the most difficult to implement. 3 is also not a bad option and would achieve the same outcome with less work, but also would only be temporary since it doesn't install the binaries.

Overall, we're about halfway there on either side if we decide to nuke my current progress with the CLI wrapper or keep it 😂 I'm sort of impartial to which ever way we decide to go, both have their pros and cons. As I said before I think even experienced nix users may end up using the `fuelup nix` CLI if it has a great UX. In its current state it already is a pretty great improvement.

**Comment by eureka-cpu** [comment]
Additional topics wrt users that already have a pre-existing nix installation:

- should we leave getting rid of nix if they no longer want fuelup, up to the user? if not, and we should uninstall nix for them, what about users who have a pre-existing nix installation?

- if we keep using nix under the hood, how should we handle pre-existing nix profiles? we could have the install script open a new terminal and create a new nix profile with the name `fuelup` and have all fuel packages point to that profile, but there may be a case where it fails and if that profile isn't created then the user may face unintended side effects if fuelup is reliant on such a profile. 

Will continue to update with my thoughts here if I have any others.
