### ISSUE TITLE
`fuelup toolchain install latest` should not fetch / reinstall versions that a user already has fetched / installed

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuelup#69]
# Summary

When running `fuelup install` the output states that it first fetches `forc` for the latest version followed by displaying the URL query.
Then it repeats the behaviour for `fuel-core`.

Lastly, it unpacks the plugins.

If I already have a version installed that matches whatever is being fetched it should do one of the following

1. Not fetch it in the first place (it seems to somehow know the latest version _and then_ it fetches it)
2. Not display the installation process for that version / plugin and instead mention that I am up-to-date and there is nothing new that has been installed.

Note: How rustup does it. First time it updates and the second time it syncs and tells me there is nothing to change.

# Screenshots

## fuelup install
![1](https://user-images.githubusercontent.com/103777923/173006408-8f412a2b-44e4-4e2d-9feb-bebba1edf67c.png)

## rustup update
![3](https://user-images.githubusercontent.com/103777923/173007159-246230ce-37ba-407f-b896-9ff597b6cec6.png)

**Comment by binggh** [comment]
This is a problem since fuelup is pretty rudimentary now and merely downloads bins to `.fuelup/bin` 😅 `rustup` stores `update-hashes` within the `.rustup` dir and checks against it to see if the hash exists before deciding if it should download a certain toolchain - will work on this after #73 is completed.
