### ISSUE TITLE
Installing `forc` should also install std and core libs

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuelup#7]
When downloading binaries for a new version of `forc` should also install the std and core libs, so that no further internet access is necessary. This could be done by cloning the repo for those deps exactly as `forc` would, or through another mechanism.

**Comment by mitchmindtree** [comment]
One approach that might be very convenient for `fuelup` could be to 1. silently `forc new` a temporary empty project, 2. immediately `forc build` it and then 3. remove the temporary project.

The `forc build` command would initialise the `~/.forc` directory and fetch the implicit `std` and `core` deps into `.forc/git/checkouts`. This would make `std` and `core` available for offline builds (once https://github.com/FuelLabs/sway/issues/895 is addressed anyway).

**Comment by otrho** [comment]
Could this all be done in RAM without making temporary files?  I guess that would need a wholesale refactoring of the `forc` I/O.

**Comment by mitchmindtree** [comment]
> Could this all be done in RAM without making temporary files? I guess that would need a wholesale refactoring of the forc I/O.

If we're to use `forc build` that would also require refactoring `sway-core` (it currently assumes a `src/` directory, `dep` files, etc).

On that note, it might be better to use `forc update` rather than `forc build` as `forc update` doesn't require actually building `std` or `core`, but still fetches them to `~/.forc`.

It's only the temporary project directory that we don't really want or need file access for (we still want to update `~/.forc`). For now I'm imagining we could just create the empty project in [`std::env::temp_dir`](https://doc.rust-lang.org/std/env/fn.temp_dir.html). If this somehow causes issues it wouldn't be tricky to create an in memory version that doesn't need the temporary project.

**Comment by binggh** [comment]
Can we just create a `Forc.toml` with the minimum configs needed (we need `name`, `authors`, `entry`, `license`), then running `forc update`, then clean up the `Forc.toml` after?

**Comment by mitchmindtree** [comment]
> Can we just create a Forc.toml with the minimum configs needed (we need name, authors, entry, license), then running forc update, then clean up the Forc.toml after?

This was [my suggestion](https://github.com/FuelLabs/fuelup/issues/7#issuecomment-1134207665) to use `forc new` (or `forc init` if it's still called that) which does exactly this.

**Comment by mitchmindtree** [comment]
Just leaving some notes following a chat with @bingcicle - using `forc update` on an empty, temporary project is almost certainly the easiest way to achieve this and ensure `core` and `std` are cached in a manner that does not require also building them.
